# Generated by Django 5.0.6 on 2025-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('activity_code', models.CharField(max_length=50)),
                ('day_type', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=10)),
                ('variable', models.CharField(max_length=100)),
                ('rate', models.FloatField(default=0)),
                ('in_value', models.FloatField(default=0)),
                ('out_value', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
